name: ci

on:
  pull_request:
  push:
    branches:
      - develop

jobs:
  ci:
    runs-on: ubuntu-latest
    outputs:
      pnpm_cache_dir: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        id: pnpm-install
        with:
          version: latest
          run_install: false

      - name: Cache Gatsby
        uses: actions/cache@v4
        with:
          path: |
            .cache
            public
          key: ${{ runner.os }}-gatsby-pnpm-build-${{ github.run_id }}
          restore-keys: ${{ runner.os }}-gatsby-pnpm-build-

      - name: Get pnpm store directory
        id: pnpm-cache
        run: echo "pnpm_cache_dir=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: ${{ runner.os }}-pnpm-store-

      - name: Install Dependencies
        run: pnpm install --prefer-offline

      - name: Lint
        run: pnpm run lint
