name: deploy

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    outputs:
      pnpm_cache_dir: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        id: pnpm-install
        with:
          version: latest
          run_install: false

      - name: Cache Gatsby
        uses: actions/cache@v3
        with:
          path: |
            .cache
            public
          key: ${{ runner.os }}-gatsby-pnpm-build-${{ github.run_id }}
          restore-keys: ${{ runner.os }}-gatsby-pnpm-build-

      - name: Get pnpm store directory
        id: pnpm-cache
        run: echo "pnpm_cache_dir=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: ${{ runner.os }}-pnpm-store-

      - name: Install Dependencies
        run: pnpm install --production --prefer-offline

      - name: Build
        run: pnpm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_branch: main
          publish_dir: ./public
          cname: kozistr.tech
          keep_files: false
          user_name: 'kozistr'
          user_email: 'kozistr@gmail.com'
          full_commit_message: ${{ github.event.head_commit.message }}
